

services:
  stereocrafter:
    build: .
    working_dir: /workspace/WEBUI-StereoCrafter
    ports:
      - "7860:7860"
    volumes:
      - ./input_source_clips:/workspace/WEBUI-StereoCrafter/input_source_clips
      - ./output_depthmaps:/workspace/WEBUI-StereoCrafter/output_depthmaps
      - ./output_splatted:/workspace/WEBUI-StereoCrafter/output_splatted
      - ./output_inpainted:/workspace/WEBUI-StereoCrafter/output_inpainted
      - ./final_videos:/workspace/WEBUI-StereoCrafter/final_videos
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
      - HF_TOKEN=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
    command: ["bash", "-c", "export PYTHONPATH=/workspace/WEBUI-StereoCrafter && bash runpod-docker-startup.sh"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  filebrowser:
    image: filebrowser/filebrowser:latest
    ports:
      - "8080:80"
    volumes:
      - ./input_source_clips:/srv/input_source_clips
      - ./output_depthmaps:/srv/output_depthmaps
      - ./output_splatted:/srv/output_splatted
      - ./output_inpainted:/srv/output_inpainted
      - ./final_videos:/srv/final_videos
      - ./filebrowser_db:/app
      - ./empty-config.json:/config/settings.json
    entrypoint: ["sh", "-c"]
    command: ["filebrowser --config /config/settings.json"]
    restart: unless-stopped

# volumes: